version: 0.8.3.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\thestrukture\IDE

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go build -o IDE -i .

artifacts:
  - path: IDE
    name: binary

deploy:
  release: IDE-$(appveyor_build_version)
  description: 'Browser accessible IDE'
  provider: GitHub
  auth_token:
    secure: 2TbJMV82B5buGm/k2GN+dhfOsVqt7QQckAS3FaYJAceofkpylFxQixf8JB3TcrDg
  artifact: binary 
  draft: false
  prerelease: false
  on:
    branch: master

